#!/usr/bin/env python3
# Assembles chapter 12's directed corner library for fp32_add4 and pins every
# expected value with the validated python models (hwmodel.py == oracle.py ==
# RTL on 2M+ vectors this session). Sources: ch08's 46-pair library (parsed
# from src/ch08/tb_corners.v) lifted to quadruples at all three tree
# positions in both orders; ch10's Q/N/Z/S/SB quads (parsed from
# tb_corners4.v); the adjacency/straddle block; the D9 witness vector; the
# {max,max,-max,-max} multiset across all 6 distinct port orders; stage-2
# ties both directions. Emits corner_list.vh + census.
import re
import sys
sys.dont_write_bytecode = True   # keep __pycache__ out of the source tree
from hwmodel import add4_tree_events, cls

SRC = '..'   # run from src/ch12/; parses ../ch08 and ../ch10 sources
Z, NZ, MAX, NMAX = 0x00000000, 0x80000000, 0x7F7FFFFF, 0xFF7FFFFF

def parse_ch08_pairs():
    txt = open(f'{SRC}/ch08/tb_corners.v').read()
    pairs = []
    for m in re.finditer(r"chk(?:_nan)?\(32'h([0-9A-Fa-f]+), 32'h([0-9A-Fa-f]+)", txt):
        pairs.append((int(m.group(1), 16), int(m.group(2), 16)))
    return pairs

def parse_ch10_quads():
    txt = open(f'{SRC}/ch10/tb_corners4.v').read()
    quads = []
    for m in re.finditer(r"a=32'h([0-9A-Fa-f]+); b=32'h([0-9A-Fa-f]+); "
                         r"c=32'h([0-9A-Fa-f]+); d=32'h([0-9A-Fa-f]+);", txt):
        quads.append(tuple(int(m.group(i), 16) for i in range(1, 5)))
    return quads

lib = []   # (family, quad)

pairs = parse_ch08_pairs()
assert len(pairs) == 46, len(pairs)
for (x, y) in pairs:
    for (p, q) in ((x, y), (y, x)):
        lib.append(('P-ab', (p, q, Z, Z)))       # pair computed at level-1 ab
        lib.append(('P-cd', (Z, Z, p, q)))       # pair computed at level-1 cd
        lib.append(('P-r',  (p, Z, q, NZ)))      # pair computed at the FINAL adder
q10 = parse_ch10_quads()
assert len(q10) == 12, len(q10)                  # Q1-3 N1-5 Z1 S1 S2 SB
for q in q10:
    lib.append(('J-ch10', q))
for k in range(16):                              # ch10's Z block + D9 witness values
    lib.append(('Z16', tuple(NZ if (k >> i) & 1 else Z for i in range(4))))
lib.append(('D9-born', (0x42F6E979, 0xC2F6E979, 0x3F800000, 0xBF800000)))
# adjacency/straddle block: bin boundaries need a vector on EACH side
lib.append(('ADJ', (0x4B000000, 0x3F000000, Z, Z)))   # d=24 (guard/round region)
lib.append(('ADJ', (0x4B000000, 0x3E800000, Z, Z)))   # d=25 (sticky-only region)
lib.append(('ADJ', (0x4B000000, 0x3E000000, Z, Z)))   # d=26 (the clamp value)
lib.append(('ADJ', (0x4B000000, 0x3D800000, Z, Z)))   # d=27 (beyond the clamp)
lib.append(('ADJ', (0x40800000, Z, 0xC07E0000, NZ)))  # inter-pair cancel shl=7
lib.append(('ADJ', (0x40800000, Z, 0xC07F0000, NZ)))  # inter-pair cancel shl=8
# the multiset, all 6 distinct port orders
seen = set()
for p in __import__('itertools').permutations([MAX, MAX, NMAX, NMAX]):
    if p not in seen:
        seen.add(p)
        lib.append(('MULTI', p))
# stage-2 ties, both directions, by both routes (screened feed and computed feed)
lib.append(('TIE-r', (0x4B800000, Z, 0x3F800000, NZ)))          # tie-down, fed
lib.append(('TIE-r', (0x4B800001, Z, 0x3F800000, NZ)))          # tie-up, fed
lib.append(('TIE-r', (0x4B000000, 0x4B000000, 0x3F000000, 0x3F000000)))  # tie-down, computed
lib.append(('TIE-r', (0x4B000001, 0x4B000000, 0x3F000000, 0x3F000000)))  # tie-up, computed

with open('corner_list.vh', 'w') as f:
    f.write(f"// GENERATED by corner_gen.py -- {len(lib)} directed quads,\n")
    f.write("// every expectation pinned by the session-validated python models\n")
    census = {}
    for fam, (a, b, c, d) in lib:
        res, _, _ = add4_tree_events(a, b, c, d)
        r, inv, ovf, inx = res
        if cls(r) in ('qnan', 'snan'):
            mode = 1 if (r & 0x3FFFFF) != 0 else 2
        else:
            mode = 0
        f.write(f"    chk(32'h{a:08X}, 32'h{b:08X}, 32'h{c:08X}, 32'h{d:08X}, "
                f"32'h{r:08X}, 3'b{inv}{ovf}{inx}, {mode});\n")
        census[fam] = census.get(fam, 0) + 1
    print("census by family:")
    total = 0
    for fam in sorted(census):
        print(f"  {fam:8s} {census[fam]}")
        total += census[fam]
    print(f"  TOTAL    {total}")
with open('corner_count.vh', 'w') as f:
    f.write(f"// GENERATED by corner_gen.py -- the count guard's expectation\n")
    f.write(f"`define NCHK_EXPECTED {len(lib)}\n")
print("NCHK =", len(lib))
