`timescale 1ns/1ps
`default_nettype none
// Chapter 12 coverage model: ch05's 34-bin model extended with every
// never-cashed dimension and re-timed to the pipelined DUT's stages
// (ch11's stage-correct qualification rule). 105 bins, sampled from the
// DUT's OWN wires; the deterministic 57-quad directed phase is checked
// against PINNED per-bin counts computed by the independent
// algorithm-level python event model (cov_pins.vh, generated by
// cov_gen.py) -- the guard that makes bin DEFINITIONS falsifiable
// (ch05's recorded M18-class blind spot, paid). Partition invariants
// cross-check the counters; the D9 never-bin is armed and asserted.
// The directed library carries bubbles INSIDE the pinned phase and a
// live-datapath first quad, and straddles every bin boundary adjacently
// (the d<=2 exponent-bucket straddle arrived last, after the ch12 review
// found it missing) -- both properties bought by surviving mutations (m4, m5
// in the README record), not by foresight.
//
// -DALL_POSITIVE: random-only, signs forced positive (ch05's
// demonstration at full scale -- must FAIL with 14 named holes).
// -DNO_DIRECTED: random-only (must FAIL with 7 named holes).
module tb_cov4;
  localparam integer NBINS = 105;
  localparam integer NDIR  = 58;
  localparam integer NPR   = 6000;   // random quads per regime, x3 regimes

  reg         clk, rst_n, in_valid;
  reg  [31:0] a, b, c, d;
  wire [31:0] result;
  wire        invalid, overflow, inexact, out_valid;

  fp32_add4 dut (.clk(clk), .rst_n(rst_n), .in_valid(in_valid),
                 .a(a), .b(b), .c(c), .d(d), .result(result),
                 .invalid(invalid), .overflow(overflow),
                 .inexact(inexact), .out_valid(out_valid));

  integer cov     [0:NBINS-1];
  integer exp_dir [0:NBINS-1];
  integer n_s1dp [0:2];   // qualified stage-1 datapath samples / instance
  integer n_s2   [0:2];   // qualified stage-2 datapath samples / instance
  integer n_tie  [0:2];
  integer d9_never, d9_armed;
  integer n_driven, n_retired;
  integer seed, i, j, k, regime, errors, holes;

  `include "cov_names.vh"

  always #5 clk = ~clk;

  initial begin : watchdog
    #20_000_000;
    $display("FAIL tb_cov4: timeout");
    $fatal(1, "timeout");
  end

  function integer fclass(input [31:0] f);
    begin
      if      (f[30:23] == 8'h00) fclass = (f[22:0] == 0) ? 0 : 1;
      else if (f[30:23] == 8'hff) fclass = (f[22:0] == 0) ? 3 : 4;
      else                        fclass = 2;
    end
  endfunction

  function integer expdbin(input [31:0] x, input [31:0] y);
    integer dd;
    begin
      dd = x[30:23] - y[30:23];       // widened to 32 bits BEFORE subtracting
      if (dd < 0) dd = -dd;
      if      (dd == 0)  expdbin = 0;
      else if (dd <= 2)  expdbin = 1;
      else if (dd < 25)  expdbin = 2;
      else               expdbin = 3;
    end
  endfunction

  // ---- stage-2 sampling for one instance, via hierarchical flat args ----
  task s2_bins(input integer inst, input right1, input [4:0] shl,
               input ng, input nr, input ns, input round_up,
               input round_renorm);
    reg tie;
    begin
      n_s2[inst] = n_s2[inst] + 1;
      cov[64 + inst*3 + (right1 ? 0 : (shl == 0 ? 1 : 2))] =
        cov[64 + inst*3 + (right1 ? 0 : (shl == 0 ? 1 : 2))] + 1;
      tie = ng & ~nr & ~ns;
      if (tie) n_tie[inst] = n_tie[inst] + 1;
      if (ng)                 cov[73+inst*6+0] = cov[73+inst*6+0] + 1;
      if (ns)                 cov[73+inst*6+1] = cov[73+inst*6+1] + 1;
      if (tie &&  round_up)   cov[73+inst*6+2] = cov[73+inst*6+2] + 1;
      if (tie && !round_up)   cov[73+inst*6+3] = cov[73+inst*6+3] + 1;
      if (round_up)           cov[73+inst*6+4] = cov[73+inst*6+4] + 1;
      if (round_renorm)       cov[73+inst*6+5] = cov[73+inst*6+5] + 1;
    end
  endtask

  task d9_chk(input ez, input es);
    begin
      if (es === 1'b0 && ez !== 1'bx) d9_armed = d9_armed + 1;
      if (ez === 1'b1 && es !== 1'b1) d9_never = d9_never + 1;
    end
  endtask

  task sample_all(input v_now);
    begin
      // ---- stage 1: operand-side bins + eff-op, this cycle's inputs ----
      if (v_now) begin
        cov[fclass(a)*5 + fclass(b)] = cov[fclass(a)*5 + fclass(b)] + 1;
        cov[25 + fclass(c)*5 + fclass(d)] = cov[25 + fclass(c)*5 + fclass(d)] + 1;
        if (fclass(a) == 2 && fclass(b) == 2)
          cov[50 + expdbin(a, b)] = cov[50 + expdbin(a, b)] + 1;
        if (fclass(c) == 2 && fclass(d) == 2)
          cov[54 + expdbin(c, d)] = cov[54 + expdbin(c, d)] + 1;
        if (dut.u_add_ab.screen === 1'b0) begin
          cov[58 + dut.u_add_ab.eff_sub] = cov[58 + dut.u_add_ab.eff_sub] + 1;
          n_s1dp[0] = n_s1dp[0] + 1;
        end
        if (dut.u_add_cd.screen === 1'b0) begin
          cov[60 + dut.u_add_cd.eff_sub] = cov[60 + dut.u_add_cd.eff_sub] + 1;
          n_s1dp[1] = n_s1dp[1] + 1;
        end
        d9_chk(dut.u_add_ab.exact_zero, dut.u_add_ab.eff_sub);
        d9_chk(dut.u_add_cd.exact_zero, dut.u_add_cd.eff_sub);
      end
      if (dut.v_ab === 1'b1) begin
        if (dut.u_add_r.screen === 1'b0) begin
          cov[62 + dut.u_add_r.eff_sub] = cov[62 + dut.u_add_r.eff_sub] + 1;
          n_s1dp[2] = n_s1dp[2] + 1;
        end
        d9_chk(dut.u_add_r.exact_zero, dut.u_add_r.eff_sub);
        // level-1 output classes (u_add_r's inputs ARE the l1 results)
        if (fclass(dut.sum_ab) == 4) cov[93] = cov[93] + 1;
        if (fclass(dut.sum_cd) == 4) cov[94] = cov[94] + 1;
        if (fclass(dut.sum_ab) == 1) cov[95] = cov[95] + 1;
        if (fclass(dut.sum_cd) == 1) cov[96] = cov[96] + 1;
      end
      // ---- stage 2 of each instance, its own valid + datapath qual ----
      if (dut.u_add_ab.vpipe[0] === 1'b1 && dut.u_add_ab.p1_screen === 1'b0) begin
        s2_bins(0, dut.u_add_ab.u_norm.right1, dut.u_add_ab.u_norm.shl,
                dut.u_add_ab.ng, dut.u_add_ab.nr, dut.u_add_ab.ns,
                dut.u_add_ab.u_round.round_up, dut.u_add_ab.u_round.round_renorm);
        if (dut.u_add_ab.ovf) cov[91] = cov[91] + 1;
      end
      if (dut.u_add_cd.vpipe[0] === 1'b1 && dut.u_add_cd.p1_screen === 1'b0) begin
        s2_bins(1, dut.u_add_cd.u_norm.right1, dut.u_add_cd.u_norm.shl,
                dut.u_add_cd.ng, dut.u_add_cd.nr, dut.u_add_cd.ns,
                dut.u_add_cd.u_round.round_up, dut.u_add_cd.u_round.round_renorm);
        if (dut.u_add_cd.ovf) cov[92] = cov[92] + 1;
      end
      if (dut.u_add_r.vpipe[0] === 1'b1 && dut.u_add_r.p1_screen === 1'b0) begin
        s2_bins(2, dut.u_add_r.u_norm.right1, dut.u_add_r.u_norm.shl,
                dut.u_add_r.ng, dut.u_add_r.nr, dut.u_add_r.ns,
                dut.u_add_r.u_round.round_up, dut.u_add_r.u_round.round_renorm);
        if (dut.u_add_r.p1_eff_sub) begin
          if (dut.u_add_r.u_norm.shl >= 1 && dut.u_add_r.u_norm.shl <= 7)
            cov[97] = cov[97] + 1;
          else if (dut.u_add_r.u_norm.shl >= 8)
            cov[98] = cov[98] + 1;
        end
        if (dut.u_add_r.p1_exact_zero) cov[99] = cov[99] + 1;
      end
      // ---- retire ----
      if (out_valid === 1'b1) begin
        cov[100 + fclass(result)] = cov[100 + fclass(result)] + 1;
        n_retired = n_retired + 1;
      end
    end
  endtask

  task slot(input valid, input [31:0] wa, input [31:0] wb,
            input [31:0] wc, input [31:0] wd);
    begin
      @(negedge clk);
      in_valid = valid;
      a = wa; b = wb; c = wc; d = wd;
      #1;
      sample_all(valid);
      if (valid) n_driven = n_driven + 1;
    end
  endtask

  task bubble;
    slot(1'b0, 32'hx, 32'hx, 32'hx, 32'hx);
  endtask

  function [31:0] gen_biased;
    input integer wide;
    integer pick;
    reg [7:0]  e;
    reg [22:0] m;
    reg        sg;
    begin
      pick = $urandom(seed) % 100;
      m    = $urandom(seed);
      if      (pick < 10) e = 8'h00;
      else if (pick < 14) e = 8'hff;
      else if (pick < 20) begin e = 8'h00; m = 23'h0; end
      else if (pick < 24) begin e = 8'hff; m = 23'h0; end
      else if (pick < 62) e = 8'h40 + ($urandom(seed) % 16);
      else if (wide)      e = 8'h01 + ($urandom(seed) % 254);
      else                e = 8'h40 + ($urandom(seed) % 16);
`ifdef ALL_POSITIVE
      sg = 1'b0;
`else
      sg = $urandom(seed);
`endif
      gen_biased = {sg, e, m};
    end
  endfunction

  function [31:0] gen_regime(input integer r);
    reg        sg;
    reg [7:0]  e;
    reg [22:0] m;
    begin
      sg = $urandom(seed);
      e  = 8'h40 + ($urandom(seed) % 4);
      m  = $urandom(seed);
`ifdef ALL_POSITIVE
      sg = 1'b0;
`endif
      case (r)
        0:       gen_regime = gen_biased(1);                  // ch05 menu
        1:       gen_regime = {sg, m[7:0], m};                // uniform-ish raw
        default: gen_regime = {sg, e, m};                     // clustered
      endcase
    end
  endfunction

  function integer count_hit;
    integer n, x;
    begin
      n = 0;
      for (x = 0; x < NBINS; x = x + 1) if (cov[x] != 0) n = n + 1;
      count_hit = n;
    end
  endfunction

  initial begin : run
    clk = 0; rst_n = 0; in_valid = 0;
    a = 32'hx; b = 32'hx; c = 32'hx; d = 32'hx;
    errors = 0; holes = 0; d9_never = 0; d9_armed = 0;
    n_driven = 0; n_retired = 0;
    for (i = 0; i < NBINS; i = i + 1) begin cov[i] = 0; exp_dir[i] = 0; end
    for (i = 0; i < 3; i = i + 1) begin
      n_s1dp[i] = 0; n_s2[i] = 0; n_tie[i] = 0;
    end
    seed = 424242; i = $urandom(seed);     // seed once, discard first draw
`include "cov_pins.vh"
    repeat (2) @(posedge clk);
    @(negedge clk) rst_n = 1;

`ifdef ALL_POSITIVE
`elsif NO_DIRECTED
`else
    // ---- phase 1: the 57-quad directed library (deterministic) ----
`include "cov_dirlist.vh"
    repeat (6) bubble;                      // drain so all 57 fully sampled
    if (n_driven !== NDIR) begin
      errors = errors + 1;
      $display("FAIL tb_cov4: directed phase drove %0d quads, expected %0d",
               n_driven, NDIR);
    end
    // ---- the M18 guard: every bin against its python-pinned count ----
    for (i = 0; i < NBINS; i = i + 1)
      if (cov[i] !== exp_dir[i]) begin
        errors = errors + 1;
        if (errors <= 10)
          $display("FAIL tb_cov4 pin: bin %0d %0s = %0d, python model pins %0d",
                   i, bname(i), cov[i], exp_dir[i]);
      end
    $display("  directed phase: %0d/%0d bins hit, pins %0s", count_hit(), NBINS,
             (errors == 0) ? "MATCH" : "MISMATCH");
`endif

    // ---- phase 2: three random regimes ----
    for (regime = 0; regime < 3; regime = regime + 1) begin
      for (i = 0; i < NPR; i = i + 1)
        slot(1, gen_regime(regime), gen_regime(regime),
                gen_regime(regime), gen_regime(regime));
      repeat (6) bubble;
      $display("  after regime %0d: %0d/%0d bins hit", regime, count_hit(), NBINS);
    end

    // ---- partition and cross invariants (definitions cross-check) ----
    for (i = 0; i < 3; i = i + 1) begin
      if (cov[64+i*3] + cov[64+i*3+1] + cov[64+i*3+2] !== n_s2[i]) begin
        errors = errors + 1;
        $display("FAIL tb_cov4: norm partition inst %0d: %0d+%0d+%0d != %0d",
                 i, cov[64+i*3], cov[64+i*3+1], cov[64+i*3+2], n_s2[i]);
      end
      if (cov[58+i*2] + cov[58+i*2+1] !== n_s1dp[i]) begin
        errors = errors + 1;
        $display("FAIL tb_cov4: eff-op partition inst %0d", i);
      end
      if (cov[73+i*6+2] + cov[73+i*6+3] !== n_tie[i]) begin
        errors = errors + 1;
        $display("FAIL tb_cov4: tie partition inst %0d: up %0d + dn %0d != ties %0d",
                 i, cov[73+i*6+2], cov[73+i*6+3], n_tie[i]);
      end
      if (cov[73+i*6+5] > cov[73+i*6+4]) begin
        errors = errors + 1;
        $display("FAIL tb_cov4: renorm > round_up at inst %0d", i);
      end
    end
    if (cov[100]+cov[101]+cov[102]+cov[103]+cov[104] !== n_retired) begin
      errors = errors + 1;
      $display("FAIL tb_cov4: result-class partition != retired");
    end
    if (n_retired !== n_driven) begin
      errors = errors + 1;
      $display("FAIL tb_cov4: %0d driven, %0d retired", n_driven, n_retired);
    end
    if (n_driven == 0) begin
      errors = errors + 1;
      $display("FAIL tb_cov4: nothing driven");
    end
    // ---- the D9 never-bin: must be armed, must be empty ----
    if (d9_armed == 0) begin
      errors = errors + 1;
      $display("FAIL tb_cov4: D9 never-bin was never armed");
    end
    if (d9_never != 0) begin
      errors = errors + 1;
      $display("FAIL tb_cov4: exact_zero fired on an effective add %0d times", d9_never);
    end
    // ---- closure ----
    for (i = 0; i < NBINS; i = i + 1)
      if (cov[i] == 0) begin
        holes = holes + 1;
        $display("  HOLE: bin %0d %0s", i, bname(i));
      end
    if (holes != 0) begin
      errors = errors + 1;
      $display("FAIL tb_cov4: %0d empty bins", holes);
    end
    if (errors == 0)
      $display("PASS tb_cov4 (%0d quads, %0d/%0d bins, pins matched, D9 never-bin armed %0d and empty)",
               n_driven, NBINS - holes, NBINS, d9_armed);
    else
      $fatal(1, "FAIL tb_cov4: %0d error(s)", errors);
    $finish;
  end
endmodule
`default_nettype wire
