`timescale 1ns/1ps
`default_nettype none
// Chapter 12 corner suite: the assembled 321-quad directed library run
// against the pipelined fp32_add4, one quad at a time with the full
// latency-4 protocol checked per vector (out_valid low for exactly 3
// cycles after the drive, high for exactly 1 carrying the result, low
// again). Every expectation is pinned by the session-validated python
// models (corner_list.vh + corner_count.vh, generated by corner_gen.py
// from ch08's 46-pair library, ch10's composition quads, and this
// chapter's new families -- regenerate and diff to audit). NaN rows:
// mode 1 compares class + quiet + payload[21:0] (never the sign); mode
// 2 (generated NaN) class + quiet only. Count-guarded against the
// generated NCHK, so a deleted row fails instead of shrinking the suite.
`include "corner_count.vh"
module tb_corners12;
  localparam integer NCHK = `NCHK_EXPECTED;

  reg         clk, rst_n, in_valid;
  reg  [31:0] a, b, c, d;
  wire [31:0] result;
  wire        invalid, overflow, inexact, out_valid;
  integer     checks, errors;

  fp32_add4 dut (.clk(clk), .rst_n(rst_n), .in_valid(in_valid),
                 .a(a), .b(b), .c(c), .d(d), .result(result),
                 .invalid(invalid), .overflow(overflow),
                 .inexact(inexact), .out_valid(out_valid));

  always #5 clk = ~clk;

  initial begin : watchdog
    #10_000_000;
    $display("FAIL tb_corners12: timeout");
    $fatal(1, "timeout");
  end

  task chk(input [31:0] wa, input [31:0] wb, input [31:0] wc, input [31:0] wd,
           input [31:0] er, input [2:0] ef, input integer mode);
    integer i;
    reg ok;
    begin
      @(negedge clk);
      in_valid = 1'b1; a = wa; b = wb; c = wc; d = wd;
      @(negedge clk);
      in_valid = 1'b0; a = 32'hx; b = 32'hx; c = 32'hx; d = 32'hx;
      // latency protocol: out_valid must be low for 3 more cycles ...
      for (i = 0; i < 3; i = i + 1) begin
        if (out_valid !== 1'b0) begin
          errors = errors + 1;
          $display("FAIL tb_corners12 %h %h %h %h: early out_valid", wa, wb, wc, wd);
        end
        @(negedge clk);
      end
      // ... then exactly one high cycle carrying the result
      if (out_valid !== 1'b1) begin
        errors = errors + 1;
        $display("FAIL tb_corners12 %h %h %h %h: out_valid=%b at latency 4",
                 wa, wb, wc, wd, out_valid);
      end else if ((^{result, invalid, overflow, inexact}) === 1'bx) begin
        errors = errors + 1;
        $display("FAIL tb_corners12 %h %h %h %h: X in outputs %h/%b%b%b",
                 wa, wb, wc, wd, result, invalid, overflow, inexact);
      end else begin
        ok = 1'b1;
        case (mode)
          0: ok = (result === er);
          1: ok = (result[30:23] === 8'hFF) && (result[22] === 1'b1) &&
                  (result[21:0] === er[21:0]);
          default: ok = (result[30:23] === 8'hFF) && (result[22] === 1'b1);
        endcase
        if (!ok || {invalid, overflow, inexact} !== ef) begin
          errors = errors + 1;
          $display("FAIL tb_corners12 %h %h %h %h: got %h/%b%b%b expected %h/%b (mode %0d)",
                   wa, wb, wc, wd, result, invalid, overflow, inexact, er, ef, mode);
        end
      end
      checks = checks + 1;
      @(negedge clk);
      if (out_valid !== 1'b0) begin
        errors = errors + 1;
        $display("FAIL tb_corners12 %h %h %h %h: out_valid stuck", wa, wb, wc, wd);
      end
    end
  endtask

  initial begin : run
    clk = 0; rst_n = 0; in_valid = 0; checks = 0; errors = 0;
    a = 32'hx; b = 32'hx; c = 32'hx; d = 32'hx;
    repeat (2) @(posedge clk);
    @(negedge clk) rst_n = 1;
`include "corner_list.vh"
    if (checks !== NCHK) begin
      errors = errors + 1;
      $display("FAIL tb_corners12: %0d checks ran, expected %0d", checks, NCHK);
    end
    if (errors == 0)
      $display("PASS tb_corners12 (%0d directed quads, python-pinned, latency protocol per vector)",
               checks);
    else
      $fatal(1, "FAIL tb_corners12: %0d error(s)", errors);
    $finish;
  end
endmodule
`default_nettype wire
