package ecs

import (
	"fmt"
	"math"
)

// =============================================================================
// NegotiationEvent represents a discrete event generated by the systems.
// These are collected per-tick and broadcast to observers.
// =============================================================================

// NegotiationEvent is emitted by systems when negotiation state transitions occur.
type NegotiationEvent struct {
	Tick         uint64
	InitiatorID  uint64
	ResponderID  uint64
	Action       string // "offer_made", "counter_offer", "accepted", "rejected", "timeout"
	Summary      string
	ProposalJSON string
}

// =============================================================================
// Systems — Functions that operate on filtered entity queries each tick.
// =============================================================================

// RunMovementSystem updates all entity positions based on their velocities.
// Entities bounce off world boundaries to stay within bounds.
func RunMovementSystem(sw *SimWorld) {
	query := sw.FilterMovement.Query()
	for query.Next() {
		pos, vel := query.Get()

		// Apply velocity
		pos.X += vel.DX * sw.DeltaTime
		pos.Y += vel.DY * sw.DeltaTime

		// Bounce off boundaries
		if pos.X < 0 {
			pos.X = -pos.X
			vel.DX = -vel.DX
		} else if pos.X > sw.Config.WorldWidth {
			pos.X = 2*sw.Config.WorldWidth - pos.X
			vel.DX = -vel.DX
		}

		if pos.Y < 0 {
			pos.Y = -pos.Y
			vel.DY = -vel.DY
		} else if pos.Y > sw.Config.WorldHeight {
			pos.Y = 2*sw.Config.WorldHeight - pos.Y
			vel.DY = -vel.DY
		}
	}
}

// RunTimeoutSystem checks all active negotiations for tick-based expiry.
// Returns events for any timeouts that occurred.
func RunTimeoutSystem(sw *SimWorld, events *[]NegotiationEvent) {
	query := sw.FilterNegotiation.Query()
	for query.Next() {
		neg, _ := query.Get()
		entity := query.Entity()

		if neg.Status != StatusIdle &&
			neg.Status != StatusAccepted &&
			neg.Status != StatusRejected &&
			neg.Status != StatusTimeout {

			if sw.CurrentTick >= neg.TickTimeout {
				*events = append(*events, NegotiationEvent{
					Tick:        sw.CurrentTick,
					InitiatorID: uint64(entity.ID()),
					ResponderID: neg.CounterPartyID,
					Action:      "timeout",
					Summary:     "Negotiation timed out",
				})
				neg.Status = StatusTimeout
				neg.CounterPartyID = 0
			}
		}
	}
}

// RunNegotiationSystem processes negotiation state machine transitions.
// Idle agents are paired up, and ongoing negotiations advance through
// offer/counter-offer rounds until acceptance, rejection, or timeout.
// Returns events for all transitions that occurred.
func RunNegotiationSystem(sw *SimWorld, events *[]NegotiationEvent) {
	// Phase 1: Reset completed negotiations back to idle.
	resetCompletedNegotiations(sw)

	// Phase 2: Pair idle agents for new negotiations.
	pairIdleAgents(sw, events)

	// Phase 3: Advance active negotiations.
	advanceNegotiations(sw, events)
}

// resetCompletedNegotiations moves agents with terminal states back to idle
// after a cooldown period (the tick after completion).
func resetCompletedNegotiations(sw *SimWorld) {
	query := sw.FilterNegotiation.Query()
	for query.Next() {
		neg, _ := query.Get()

		if neg.Status == StatusAccepted ||
			neg.Status == StatusRejected ||
			neg.Status == StatusTimeout {
			// Reset after one tick in terminal state
			if sw.CurrentTick > neg.TickTimeout {
				neg.Status = StatusIdle
				neg.CounterPartyID = 0
				neg.ProposalJSON = ""
				neg.RoundsCompleted = 0
			}
		}
	}
}

// idleAgent holds entity info for pairing.
type idleAgent struct {
	entityID uint64
	posX     float64
	posY     float64
}

// pairIdleAgents finds idle agents and pairs nearby ones for negotiation.
func pairIdleAgents(sw *SimWorld, events *[]NegotiationEvent) {
	// Collect idle agents
	var idle []idleAgent

	query := sw.FilterAll.Query()
	for query.Next() {
		pos, _, _, neg, _ := query.Get()
		entity := query.Entity()

		if neg.Status == StatusIdle {
			idle = append(idle, idleAgent{
				entityID: uint64(entity.ID()),
				posX:     pos.X,
				posY:     pos.Y,
			})
		}
	}

	// Shuffle for fairness
	sw.rng.Shuffle(len(idle), func(i, j int) {
		idle[i], idle[j] = idle[j], idle[i]
	})

	// Pair agents based on proximity (greedy nearest-neighbor).
	// Only pair a fraction of idle agents each tick to avoid all agents
	// negotiating simultaneously.
	paired := make(map[uint64]bool)
	maxPairsPerTick := len(idle) / 4
	if maxPairsPerTick < 1 {
		maxPairsPerTick = 1
	}
	pairsCreated := 0

	for i := 0; i < len(idle) && pairsCreated < maxPairsPerTick; i++ {
		if paired[idle[i].entityID] {
			continue
		}

		// Find the nearest un-paired idle agent
		bestIdx := -1
		bestDist := math.MaxFloat64

		for j := i + 1; j < len(idle); j++ {
			if paired[idle[j].entityID] {
				continue
			}
			dx := idle[i].posX - idle[j].posX
			dy := idle[i].posY - idle[j].posY
			dist := dx*dx + dy*dy
			if dist < bestDist {
				bestDist = dist
				bestIdx = j
			}
		}

		if bestIdx == -1 {
			break
		}

		// Pair them: initiator makes an offer to responder
		initiatorID := idle[i].entityID
		responderID := idle[bestIdx].entityID

		paired[initiatorID] = true
		paired[responderID] = true

		// Update initiator state — need to query by entity
		startNegotiation(sw, initiatorID, responderID, events)
		pairsCreated++
	}
}

// startNegotiation sets up a new negotiation between two entities.
func startNegotiation(sw *SimWorld, initiatorID, responderID uint64, events *[]NegotiationEvent) {
	// We need to iterate to find and update these specific entities.
	// This is a limitation of the query-based approach — we set flags
	// and resolve them in the next query pass.
	query := sw.FilterNegotiation.Query()
	for query.Next() {
		neg, _ := query.Get()
		entity := query.Entity()
		eid := uint64(entity.ID())

		if eid == initiatorID {
			neg.Status = StatusOffering
			neg.CounterPartyID = responderID
			neg.TickStarted = sw.CurrentTick
			neg.TickTimeout = sw.CurrentTick + sw.Config.NegotiationTimeoutTicks
			neg.RoundsCompleted = 0
			neg.ProposalJSON = `{"type":"initial_offer"}`
		} else if eid == responderID {
			neg.Status = StatusCountering
			neg.CounterPartyID = initiatorID
			neg.TickStarted = sw.CurrentTick
			neg.TickTimeout = sw.CurrentTick + sw.Config.NegotiationTimeoutTicks
			neg.RoundsCompleted = 0
		}
	}

	*events = append(*events, NegotiationEvent{
		Tick:         sw.CurrentTick,
		InitiatorID:  initiatorID,
		ResponderID:  responderID,
		Action:       "offer_made",
		Summary:      "New negotiation started",
		ProposalJSON: `{"type":"initial_offer"}`,
	})
}

// pendingTransfer records a cash transfer to apply after the query closes.
type pendingTransfer struct {
	fromID uint64
	toID   uint64
	amount float64
}

// advanceNegotiations progresses active negotiations through rounds.
func advanceNegotiations(sw *SimWorld, events *[]NegotiationEvent) {
	var transfers []pendingTransfer

	query := sw.FilterNegotiation.Query()
	for query.Next() {
		neg, inv := query.Get()
		entity := query.Entity()
		eid := uint64(entity.ID())

		switch neg.Status {
		case StatusOffering:
			// The offering agent waits for a response.
			// Simulate the counter-party deciding to counter or accept.
			// Decision is based on a random roll — strategy-dependent in future.
			if neg.RoundsCompleted > 0 {
				roll := sw.rng.Float64()
				if roll < 0.3 {
					// Accept the offer
					neg.Status = StatusAccepted
					neg.TickTimeout = sw.CurrentTick // mark completion tick

					// Debit the initiator immediately; credit deferred
					transferAmount := 10.0
					if inv.Cash >= transferAmount {
						inv.Cash -= transferAmount
						transfers = append(transfers, pendingTransfer{
							fromID: eid,
							toID:   neg.CounterPartyID,
							amount: transferAmount,
						})
					}

					*events = append(*events, NegotiationEvent{
						Tick:        sw.CurrentTick,
						InitiatorID: eid,
						ResponderID: neg.CounterPartyID,
						Action:      "accepted",
						Summary:     "Offer accepted",
					})
				} else if roll < 0.5 {
					// Reject
					neg.Status = StatusRejected
					neg.TickTimeout = sw.CurrentTick
					*events = append(*events, NegotiationEvent{
						Tick:        sw.CurrentTick,
						InitiatorID: eid,
						ResponderID: neg.CounterPartyID,
						Action:      "rejected",
						Summary:     "Offer rejected",
					})
				}
				// else: continue waiting
			}

		case StatusCountering:
			// Counter-party decides whether to counter-offer or accept.
			neg.RoundsCompleted++
			roll := sw.rng.Float64()
			if roll < 0.2 {
				// Accept
				neg.Status = StatusAccepted
				neg.TickTimeout = sw.CurrentTick
				*events = append(*events, NegotiationEvent{
					Tick:        sw.CurrentTick,
					InitiatorID: neg.CounterPartyID,
					ResponderID: eid,
					Action:      "accepted",
					Summary:     "Counter-party accepted",
				})
			} else if roll < 0.4 {
				// Reject
				neg.Status = StatusRejected
				neg.TickTimeout = sw.CurrentTick
				*events = append(*events, NegotiationEvent{
					Tick:        sw.CurrentTick,
					InitiatorID: neg.CounterPartyID,
					ResponderID: eid,
					Action:      "rejected",
					Summary:     "Counter-party rejected",
				})
			} else {
				// Counter-offer
				neg.Status = StatusOffering
				*events = append(*events, NegotiationEvent{
					Tick:         sw.CurrentTick,
					InitiatorID:  eid,
					ResponderID:  neg.CounterPartyID,
					Action:       "counter_offer",
					Summary:      "Counter-offer made",
					ProposalJSON: `{"type":"counter_offer","round":` + fmt.Sprintf("%d", neg.RoundsCompleted) + `}`,
				})
			}
		}
	}
	// Query is now closed — safe to open a new one for transfers.

	// Apply deferred transfers
	if len(transfers) > 0 {
		applyTransfers(sw, transfers)
	}
}

// applyTransfers credits cash to recipient entities after the main query closes.
func applyTransfers(sw *SimWorld, transfers []pendingTransfer) {
	// Build a lookup of credits by entity ID
	credits := make(map[uint64]float64)
	for _, t := range transfers {
		credits[t.toID] += t.amount
	}

	query := sw.FilterNegotiation.Query()
	for query.Next() {
		_, inv := query.Get()
		entity := query.Entity()
		eid := uint64(entity.ID())

		if amount, ok := credits[eid]; ok {
			inv.Cash += amount
			delete(credits, eid)
			if len(credits) == 0 {
				query.Close() // Must close to release world lock
				return
			}
		}
	}
}

