on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  generate_readme_stats:
    name: Generates ReadMe Images
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year 
          
          plugin_anilist: yes
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, characters 
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
          plugin_anilist_shuffle: yes
          plugin_anilist_user: freedrone
