on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  generate_readme_stats:
    name: Generates ReadMe Images
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year 
          # Language Analysis
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: Cihan Eran, erancihan, erancihan@gmail.com
          plugin_languages_ignored: >-
            shell
          # AniList Conf
          plugin_anilist: yes
          plugin_anilist_medias: anime, manga
          plugin_anilist_sections: favorites, characters 
          plugin_anilist_limit: 2
          plugin_anilist_limit_characters: 22
          plugin_anilist_shuffle: no
          plugin_anilist_user: freedrone
          # GitHub Token
          token: ${{ secrets.METRICS_TOKEN }}
